TRAIN_CONFIGS:
  out_dir: siren_sampling
  iterations: 5000
  save_interval: 100
  mt_save_interval: 100
  gpu_devices: "0"
  seed: 42
  sampling_path: sampling_history.pkl
  loss_path: loss_history.pkl
  save_name: siren
  no_io: 0

EXP_CONFIGS:
  strategy_type: nint
  optimizer_type: adam
  lr_scheduler_type: constant

nint:
  batch_size_scheduler: constant
  mt_ratio: 0.2
  top_k: 1
  sample_interval: dense

NETWORK_CONFIGS:
  lr: 1e-4
  data_range: 0
  coord_mode: 2
  rff_std: 10

DATASET_CONFIGS:
  data_type: image
  file_path: images/01.png
  color_mode: RGB
  img_size: null

WANDB_CONFIGS:
  use_wandb: 0
  wandb_project: YOUR_PROJECT_NAME
  wandb_entity: YOUR_USERNAME
  group: nint_image_training
  log_loss: 1
  log_psnr: 1
  log_ssim: 1
  log_lpips: 0
  log_time_metrics: 1
  log_images: 1
  log_gt_image: 1
  log_reconstruction: 1
  log_tinted: 1
  log_selected: 0
  log_ntk: 0
  ntk_log_interval: 500
  image_log_time_interval: 10

METRIC_LOGGING:
  save_local: 1
  log_psnr: 1
  log_ssim: 1
  log_lpips: 1

defaults:
  - model_config: siren

hydra:
  run:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}
    
  sweep:
    dir: outputs/${TRAIN_CONFIGS.out_dir}/hydra_configs/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}